#ifndef GEOM_MODEL_SRC_UTIL_STD_DEFINES_H_
#define GEOM_MODEL_SRC_UTIL_STD_DEFINES_H_

#ifndef _USE_MATH_DEFINES
#define _USE_MATH_DEFINES
#endif

#ifndef M_PI
#define M_PI 3.14159265359
#endif

#endif // GEOM_MODEL_SRC_UTIL_STD_DEFINES_H_
